# Generated by Django 5.0 on 2024-01-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
