# Generated by Django 5.0 on 2024-01-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0004_songs_delete_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
