# Generated by Django 5.0 on 2024-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0005_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default='cover_images/default.jpg', upload_to='cover_images/'),
        ),
    ]
