# Generated by Django 5.0.1 on 2024-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0007_album_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
