# Generated by Django 5.0.1 on 2024-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0008_album_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
