# Generated by Django 5.0.1 on 2024-01-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0009_remove_album_album_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
