# Generated by Django 5.0.1 on 2024-01-25 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0010_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='cover_images/')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
