# Generated by Django 5.0.1 on 2024-01-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpotiFind', '0012_alter_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_image',
        ),
    ]
